name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  firmware:
    name: Firmware
    uses: ./.github/workflows/firmware.yml
    with:
      build-type: Release
      retention-days: 7

  asio:
    name: ASIO Driver
    uses: ./.github/workflows/asio.yml
    with:
      build-type: Release
      retention-days: 7
